# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

xMatrix <- function(xVector, polyOrder) {
    .Call('_DCSmooth_xMatrix', PACKAGE = 'DCSmooth', xVector, polyOrder)
}

cumsum_part_reverse <- function(vec_1, vec_2) {
    .Call('_DCSmooth_cumsum_part_reverse', PACKAGE = 'DCSmooth', vec_1, vec_2)
}

specDens_cpp <- function(Y, omega) {
    .Call('_DCSmooth_specDens_cpp', PACKAGE = 'DCSmooth', Y, omega)
}

acfMatrix_quarter2 <- function(y_Mat) {
    .Call('_DCSmooth_acfMatrix_quarter2', PACKAGE = 'DCSmooth', y_Mat)
}

acfMatrix_quarter <- function(y_Mat) {
    .Call('_DCSmooth_acfMatrix_quarter', PACKAGE = 'DCSmooth', y_Mat)
}

acfMatrix_cpp <- function(y_Mat) {
    .Call('_DCSmooth_acfMatrix_cpp', PACKAGE = 'DCSmooth', y_Mat)
}

globalBndw_cpp <- function(acfMat, hLag) {
    .Call('_DCSmooth_globalBndw_cpp', PACKAGE = 'DCSmooth', acfMat, hLag)
}

specInt00_cpp <- function(acfMat) {
    .Call('_DCSmooth_specInt00_cpp', PACKAGE = 'DCSmooth', acfMat)
}

specIntDrv_cpp <- function(acfMat, drv1, drv2, hLag) {
    .Call('_DCSmooth_specIntDrv_cpp', PACKAGE = 'DCSmooth', acfMat, drv1, drv2, hLag)
}

localBndw_cpp <- function(acfMat, hLag, omega) {
    .Call('_DCSmooth_localBndw_cpp', PACKAGE = 'DCSmooth', acfMat, hLag, omega)
}

specDensEst_cpp <- function(acfMat, drv, hLag, omega) {
    .Call('_DCSmooth_specDensEst_cpp', PACKAGE = 'DCSmooth', acfMat, drv, hLag, omega)
}

fourier_mat <- function(Lx, Lt, omega) {
    .Call('_DCSmooth_fourier_mat', PACKAGE = 'DCSmooth', Lx, Lt, omega)
}

bartlett_mat <- function(Lx, Lt, drv1, drv2, power) {
    .Call('_DCSmooth_bartlett_mat', PACKAGE = 'DCSmooth', Lx, Lt, drv1, drv2, power)
}

KRSmooth_matrix2 <- function(yMat, h, drv, kernFcnPtr) {
    .Call('_DCSmooth_KRSmooth_matrix2', PACKAGE = 'DCSmooth', yMat, h, drv, kernFcnPtr)
}

KR_dcs_const0 <- function(yMat, hVec, drvVec, kernFcnPtrX, kernFcnPtrT) {
    .Call('_DCSmooth_KR_dcs_const0', PACKAGE = 'DCSmooth', yMat, hVec, drvVec, kernFcnPtrX, kernFcnPtrT)
}

KRSmooth_matrix <- function(yMat, h, drv, kernFcnPtr) {
    .Call('_DCSmooth_KRSmooth_matrix', PACKAGE = 'DCSmooth', yMat, h, drv, kernFcnPtr)
}

KR_dcs_const1 <- function(yMat, hVec, drvVec, kernFcnPtrX, kernFcnPtrT) {
    .Call('_DCSmooth_KR_dcs_const1', PACKAGE = 'DCSmooth', yMat, hVec, drvVec, kernFcnPtrX, kernFcnPtrT)
}

kernel_fcn_assign <- function(fstr) {
    .Call('_DCSmooth_kernel_fcn_assign', PACKAGE = 'DCSmooth', fstr)
}

kernel_fcn_use <- function(x, q, xpsexp) {
    .Call('_DCSmooth_kernel_fcn_use', PACKAGE = 'DCSmooth', x, q, xpsexp)
}

weight_fcn_assign <- function(fstr) {
    .Call('_DCSmooth_weight_fcn_assign', PACKAGE = 'DCSmooth', fstr)
}

kern_fcn_M200 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_M200', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_M210 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_M210', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_M220 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_M220', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_M321 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_M321', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_M420 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_M420', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_M421 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_M421', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_M422 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_M422', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_M533 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_M533', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_M644 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_M644', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_MW200 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_MW200', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_MW210 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_MW210', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_MW220 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_MW220', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_MW320 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_MW320', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_MW321 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_MW321', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_MW420 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_MW420', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_MW421 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_MW421', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_MW422 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_MW422', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_MW533 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_MW533', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_MW644 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_MW644', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_T220 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_T220', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_T321 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_T321', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_T420 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_T420', PACKAGE = 'DCSmooth', uVec, q)
}

kern_fcn_T422 <- function(uVec, q = 1) {
    .Call('_DCSmooth_kern_fcn_T422', PACKAGE = 'DCSmooth', uVec, q)
}

LPSmooth_matrix2_BMod <- function(yMat, h, polyOrder, drv, mu, weightFcnPtr) {
    .Call('_DCSmooth_LPSmooth_matrix2_BMod', PACKAGE = 'DCSmooth', yMat, h, polyOrder, drv, mu, weightFcnPtr)
}

LP_dcs_const0_BMod <- function(yMat, hVec, polyOrderVec, drvVec, muVec, weightFcnPtr_x, weightFcnPtr_t) {
    .Call('_DCSmooth_LP_dcs_const0_BMod', PACKAGE = 'DCSmooth', yMat, hVec, polyOrderVec, drvVec, muVec, weightFcnPtr_x, weightFcnPtr_t)
}

LPSmooth_matrix_BMod <- function(yMat, h, polyOrder, drv, mu, weightFcnPtr) {
    .Call('_DCSmooth_LPSmooth_matrix_BMod', PACKAGE = 'DCSmooth', yMat, h, polyOrder, drv, mu, weightFcnPtr)
}

LP_dcs_const1_BMod <- function(yMat, hVec, polyOrderVec, drvVec, muVec, weightFcnPtr_x, weightFcnPtr_t) {
    .Call('_DCSmooth_LP_dcs_const1_BMod', PACKAGE = 'DCSmooth', yMat, hVec, polyOrderVec, drvVec, muVec, weightFcnPtr_x, weightFcnPtr_t)
}

ar_coef <- function(ar, ma, d, k) {
    .Call('_DCSmooth_ar_coef', PACKAGE = 'DCSmooth', ar, ma, d, k)
}

ARMA_to_AR <- function(phi, psi, K) {
    .Call('_DCSmooth_ARMA_to_AR', PACKAGE = 'DCSmooth', phi, psi, K)
}

sarma_rss <- function(theta, R_mat, model_order) {
    .Call('_DCSmooth_sarma_rss', PACKAGE = 'DCSmooth', theta, R_mat, model_order)
}

sfarima_rss <- function(theta, R_mat, model_order) {
    .Call('_DCSmooth_sfarima_rss', PACKAGE = 'DCSmooth', theta, R_mat, model_order)
}

