# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastLm <- function(y, x, w) {
    .Call(`_DCSmooth_fastLm`, y, x, w)
}

test <- function(x, q) {
    .Call(`_DCSmooth_test`, x, q)
}

test3 <- function(x) {
    .Call(`_DCSmooth_test3`, x)
}

rcpparma_hello_world <- function() {
    .Call(`_DCSmooth_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_DCSmooth_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_DCSmooth_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_DCSmooth_rcpparma_bothproducts`, x)
}

