# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LPSmooth_grid <- function(y, h, polyOrder) {
    .Call(`_DCSmooth_LPSmooth_grid`, y, h, polyOrder)
}

LPSmooth_nongrid <- function(y, x, h, polyOrder) {
    .Call(`_DCSmooth_LPSmooth_nongrid`, y, x, h, polyOrder)
}

test <- function(x, q) {
    .Call(`_DCSmooth_test`, x, q)
}

test3 <- function(a, b) {
    .Call(`_DCSmooth_test3`, a, b)
}

